### PR TITLE
ansible: add adoptopenjdk tag back to riscv role and explicitly run o…

### PR DESCRIPTION
**Pull request by gdams**
…n docker

### CODE REVIEW

**Comment by Willsparker** [comment]
Can you use both `--tags` and `--skip-tags`? I haven't tried that before and I can't see it in the documentation: https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html

**Comment by gdams** [comment]
hmm apparently not... that PR job failed

**Comment by gdams** [comment]
hmm yeah @sxa that is not going to work... I'm not sure how else to proceed here?

**Comment by gdams** [comment]
Trying another solution, it's a bit of a hack having to run the `ansible-playbook` command twice but I think it's the only way to make this work...

**Comment by sxa** [comment]
Maybe adjust it to do a second playbook run that only runs that one role? It won't take effect on any systems other than Cent6 so will end up as a no-pop on other distributions

**Comment by gdams** [comment]
okay, @sxa @Willsparker it worked! PTAL

**Pull request merged**
