### PR TITLE
vagrant: Force win2012r2 to use tls1.2 in provision script

### PR DESCRIPTION
**Pull request by Willsparker**
Fixes: #1858 

Also updates the comments to better reflect what's happening in the VF

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [x] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access). In progress: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/993/

### CODE REVIEW

**Comment by Willsparker** [comment]
VPC run was able to boot the VM with the provision script as it's meant to, and started the playbook as usual.

**Review by sxa — APPROVED** [review]
Interesting ... Do we know what change caused this to be a problem? Was it after of the ansible reinstallations or has there been a change in the virtualbox image?

And therefore under what circumstances might it be seen outside a vagrant environment (i.e. do we need to document it somewhere?)

**Comment by Willsparker** [comment]
I'm unsure of the cause - the problem occurs when I run a Windows Vagrant VM on my laptop too, so I don't think it's the Ansible re-installation. From the looks of https://app.vagrantup.com/mwrock/boxes/Windows2012R2 , the image hasn't been changed either. 
A quick google doesn't show any other people having this issue in the past month either. 

As for effects outside a Vagrant environment - I just tried `Invoke-WebRequest` on both `test-azure-win2012r2-x64-1` and `build-alibaba-win2012r2-x64-1` and they have the same issue, so yeah, I'll document it somewhere, as part of this PR.

**Comment by sxa** [comment]
This makes me nervous because it doesn't appear to be reproducible from @Haroon-Khel's ansible client (also macos)

**Comment by Willsparker** [comment]
This particular fix has nothing to do with Ansible - this fix is so the provisioning script at the beginning of the Windows Vagrantfile can be run - and the command isn't persistent after the shell it's in has been closed, so it won't affect the playbooks

**Comment by sxa** [comment]
LGTM (other than whatever has caused the CentOS check to fail) - and thanks for including the doc updates too :-)

I feel we still need a story around the `7-Zip` thing. Would be good to know if that is related to whether cygwin is on the box

**Comment by Willsparker** [comment]
Okay, merging. 

This [Windows VPC run](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/996/) succeeded, without any issues, so it may have just been a coincidence that `7-zip` failed? Not sure, but I'll keep an eye on it.

Ref: C6 check, a `tar.xz` has been removed from https://ci.adoptopenjdk.net/userContent/gcc/ ; asked about it [in Slack](https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1611733179055400)

**Pull request merged**
