### PR TITLE
Add XML::Parser module into playbooks

### PR DESCRIPTION
**Pull request by renfeiw**
- Test framework will require XML::Parser module to parse playlist.xml
files

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
@gdams Could you please review this PR? Thanks!

**Comment by renfeiw** [comment]
We also need help to install this perl module on the existing machines: https://ci.adoptopenjdk.net/computer/

**Comment by karianna** [comment]
@renfeiw What's the purpose of this addition?

**Comment by renfeiw** [comment]
We wants to update the test framework (testKitGen) to use a standard XML parser to parse playlist.xml files.

**Comment by gdams** [comment]
can we not use jenkins to parse the xml data?

**Comment by renfeiw** [comment]
We are using the test framework to parse xml data and generate the make files. In order for it to work, we need to install perl XML::Parser module on the jenkins machines.

**Comment by renfeiw** [comment]
The conflict is solved, please take a look.

**Comment by renfeiw** [comment]
Close this PR, as Brad will address this requirement in another issue.

**Pull request closed without merging**
