### PR TITLE
inventory: add missing inspira SPARC systems

### PR DESCRIPTION
**Pull request by sxa**
As per slack discussion @gdams it would be good to understand if [build machine -1](https://ci.adoptopenjdk.net/computer/build-inspira-solaris10u11-sparcv9-1/) is supposed to be online as it is not currently.

Initial test system was added (commented out) under https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1338

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Comment by karianna** [comment]
@sxa Linter not happy

**Comment by sxa** [comment]
Linter issues resolved. Will merge once other checks complete

**Comment by sxa** [comment]
Checks appeared jammed in queueing state

**Comment by sxa** [comment]
Force pushing commit message change to re-queue

**Comment by sxa** [comment]
Happy @karianna ?

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
