### PR TITLE
unixPB: Update checksum for CentOS/RHEL docker repo

### PR DESCRIPTION
**Pull request by sxa**
Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM - I assume the linter is still borked.

**Review by Willsparker — CHANGES_REQUESTED** [review]
I'm still getting the old checksum when I `wget` the repo: 
```
2021-02-16 07:37:45 (87.8 MB/s) - ‘docker-ce.repo’ saved [1919/1919]

will@will-XPS-13-9360:~/Documents/1883/ansible$ sha256sum docker-ce.repo 
8ab5599eef0afcac10cbd3e8670873efee20fcceb5fb3526a62edeade603cec7  docker-ce.repo
```

**Comment by sxa** [comment]
> I'm still getting the old checksum when I `wget` the repo: 
> ```
> 2021-02-16 07:37:45 (87.8 MB/s) - ‘docker-ce.repo’ saved [1919/1919]
> 
> will@will-XPS-13-9360:~/Documents/1883/ansible$ sha256sum docker-ce.repo 
> 8ab5599eef0afcac10cbd3e8670873efee20fcceb5fb3526a62edeade603cec7  docker-ce.repo
> ```

Since you've got our can you attach the file with the old checksum to those PR please?

**Comment by sxa** [comment]
> LGTM - I assume the linter is still borked.

Yes as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1926

**Comment by Willsparker** [comment]
This is the contents of the `docker-ce.repo` that still has the old checksum:
```
[docker-ce-stable]
name=Docker CE Stable - $basearch
baseurl=https://download.docker.com/linux/centos/$releasever/$basearch/stable
enabled=1
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg

[docker-ce-stable-debuginfo]
name=Docker CE Stable - Debuginfo $basearch
baseurl=https://download.docker.com/linux/centos/$releasever/debug-$basearch/stable
enabled=0
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg

[docker-ce-stable-source]
name=Docker CE Stable - Sources
baseurl=https://download.docker.com/linux/centos/$releasever/source/stable
enabled=0
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg

[docker-ce-test]
name=Docker CE Test - $basearch
baseurl=https://download.docker.com/linux/centos/$releasever/$basearch/test
enabled=0
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg

[docker-ce-test-debuginfo]
name=Docker CE Test - Debuginfo $basearch
baseurl=https://download.docker.com/linux/centos/$releasever/debug-$basearch/test
enabled=0
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg

[docker-ce-test-source]
name=Docker CE Test - Sources
baseurl=https://download.docker.com/linux/centos/$releasever/source/test
enabled=0
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg

[docker-ce-nightly]
name=Docker CE Nightly - $basearch
baseurl=https://download.docker.com/linux/centos/$releasever/$basearch/nightly
enabled=0
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg

[docker-ce-nightly-debuginfo]
name=Docker CE Nightly - Debuginfo $basearch
baseurl=https://download.docker.com/linux/centos/$releasever/debug-$basearch/nightly
enabled=0
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg

[docker-ce-nightly-source]
name=Docker CE Nightly - Sources
baseurl=https://download.docker.com/linux/centos/$releasever/source/nightly
enabled=0
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg
```
I was unable to attach it due to GitHub not supporting that file type

**Comment by sxa** [comment]
> I was unable to attach it due to GitHub not supporting that file type

You can always add `.txt` or `gzip` it, but thanks - that worked well enough :-)

**Comment by sxa** [comment]
Maybe they did something and reverted it. Was definitely having issues with the checksum yesterday somewhere after downloading it to verify but it looks to be working today. Closing

**Pull request closed without merging**
