### PR TITLE
Use retries on ant_contrib URL to resolve sourceforge URL connections…

### PR DESCRIPTION
**Pull request by joeheb1970**
… issues

### CODE REVIEW

**Comment by karianna** [comment]
@joeheb1970 - needs rebasing.

**Comment by joeheb1970** [comment]
please help......im lost......cant figure anything out......limited pc time....and need my family back....im just frazzled......

**Comment by karianna** [comment]
@joeheb1970 sorry to hear that!  Your rebase has worked but there are some test failures:


ERROR! Syntax Error while loading YAML.
  did not find expected '-' indicator
The error appears to be in '/home/travis/build/AdoptOpenJDK/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml': line 30, column 2, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    validate_certs: t
 retry_antcontrib
 ^ here

**Comment by Willsparker** [comment]
I don't believe this PR is needed - https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/6c7c9d3c06205f81e856838f7181b497d0e70e08/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml#L23

The retries have already been put in with #1000 :-)

**Comment by karianna** [comment]
@Willsparker - you can close this if you're confident it's not needed.

**Comment by karianna** [comment]
This is actually SPAM

**Pull request closed without merging**
