### PR TITLE
unixPB: Various small fixes to get AWX running cleanly

### PR DESCRIPTION
**Pull request by Willsparker**
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1990#issuecomment-790422413

Various issues found when running the playbooks on all the machines:
  - Remove installation of locales for RHEL, entirely. `glibc-common` provides the locale specific functions now, it seems.
  - Update some URLs for dependencies for RHEL7 aarch64 (The version has been updated in the package repo)
  - Install `nagios-plugins` for RHEL8/x64, as opposed to `nagios-plugins-all`, as the latter has some dependencies that can be fulfilled.

I'm sure there will be more once I've done the AWX `test*centos*` and `test*ubuntu*` runs, so I'll keep this in draft for now. 

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by sxa** [comment]
> Remove installation of locales for RHEL, entirely. glibc-common provides the locale specific functions now, it seems.

Is that ok for 6 as well?

**Comment by Willsparker** [comment]
> Is that ok for 6 as well?

Yep, apparently! `test-ibmcloud-rhel6-x64-1` didn't have it available in the repos, but it already had `glibc-common` installed and could run `locales -a`

**Comment by Willsparker** [comment]
I've gone through all of the Linux runs with AWX, and this seems to be the fixes required. Ready to review :+1:

**Comment by Willsparker** [comment]
Ref the Docker check - it looks like a network hiccup? The `libgcc-4.4.7-23.el6.i686.rpm` package is still in https://vault.centos.org/6.10//os/x86_64/Packages/ , so it should be able to find it..

**Comment by sxa** [comment]
A VPC run just as a final check :-) https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1096

**Review by sxa — APPROVED** [review]
Debian looks generall 

> A VPC run just as a final check :-) https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1097

Debian10 looks generall broken, Windows 2012 and CentOS6 VMs didn't seem to startup properly so I think this is probably ok to go in :-)

**Pull request merged**
