### PR TITLE
winPB: add arm components to VS2019 role

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] FAQ.md updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] inventory changes, ensure bastillion is updated accordingly

### CODE REVIEW

**Comment by Willsparker** [comment]
I've started a [VPC run](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/969/OS=Win2012,label=vagrant/console). Whats the ARM components for?

**Comment by gdams** [comment]
@Willsparker it's for the windows arm64 build: https://github.com/AdoptOpenJDK/openjdk-build/pull/2117

**Comment by Willsparker** [comment]
Alright - I'll put review it once the run is done :-)

**Review by Willsparker — APPROVED** [review]
VPC passed! LGTM :-)

**Pull request merged**
