### PR TITLE
Updated for Alpine Linux 3.13 based on Part 1 & 2 instructions

### PR DESCRIPTION
**Pull request by ZM202**
##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by ZM202** [comment]
alp 313 wasn't showing up earlier. It should be all set. Please let me know if you're not seeing it. Thanks.

**Comment by smlambert** [comment]
@sxa or @Haroon-Khel - would you be able to give some assistance to @ZM202 to move this PR forward please?

**Comment by sxa** [comment]
@smlambert I'd be a little reluctant to add test systems with a new OS three days before lockdown so would prefer this not to go in and live before we've completed the releases next week unless you think it's important to test on it for this GA.

**Comment by sxa** [comment]
@ZM202 Useful tip - if you're submitting a PR to fix a particular issue it's worth using one of the special github keywords to link them together: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

I'll do it here: Fixed https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2064

The change looks good at a quick glance but either myself or Haroon will be able to review it properly in the next week - thanks for your submission :+1:

**Comment by sxa** [comment]
(NOTE to anyone else reviewing this, the macos playbook check failure is something that has already been fixed elsewhere so should not necessarily block this PR)

**Comment by ZM202** [comment]
Thanks for the feedback @sxa Will incorporate them for the future.

**Review by sxa — APPROVED** [review]
I've just done a quick check to verify that the dockerfile works with 3.13 and it looks good - thanks for fixing (and apologies that I forgot to come back and review this when I said I would - feel free to chase me up if that happens again!)

**Pull request merged**
