### PR TITLE
Ram increase for Vagrant VMs

### PR DESCRIPTION
**Pull request by sxa555**
Increase RAM available to Vagrant machines (especially Windows) and cap the CPU on the hypervisor for each individual one so that the build jobs don't overwhelm it

### CODE REVIEW

**Comment by karianna** [comment]
@sxa555 Will need a rebase

**Comment by sxa555** [comment]
@karianna Can you see the rebase/resolve conflicts button on the UI here? It's greyed out for me ...
image

**Comment by Willsparker** [comment]
@sxa555 @karianna The button is greyed out because it says "These conflicts are too complex to solve in the web editor". I imagine it's because `Vagrantfile.SLES12` was renamed / removed and replaced with `Vagrantfile.SUSE12`

**Comment by sxa555** [comment]
Well spotted - resolved and testing under https://ci.adoptopenjdk.net/view/work%20in%20progress/job/VagrantPlaybookCheck/369/

**Pull request merged**
