### PR TITLE
inventory: Add alibaba aarch64 machines

### PR DESCRIPTION
**Pull request by sxa**
Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly (Not nagios yet due to playbook issue)

### CODE REVIEW

**Review by Willsparker — COMMENTED** [review]
Was there an issue tracking the creation of these? I assume these were the reason for #1901 , as they're not in Nagios.
Also, why are you adding a packet machine?

**Comment by sxa** [comment]
Possible we don't have an issue for it as th details were given to me in Slack. The alibaba machines are Ubuntu 18.04 but I have the nagios roles removed in AWX just now so they won't have been executed.

The packet machine I could remove for now as I haven't decided if I'm going to make it live yet but adding it just lets me remember what the IP address is, but yes that was the system where I hit the 20.04 issue.

**Comment by Willsparker** [comment]
fair enough, just making sure those details are documented somewhere ;) Ref Nagios, the U20/aarch64 issue should hopefully be fixed with #1912

**Comment by karianna** [comment]
OK to merge?

**Comment by sxa** [comment]
> OK to merge?

I'll merge once I get an affirmative review :-)

**Review by Willsparker — APPROVED** [review]
LGTM, assuming that the test and build machine have the same IP on purpose

**Comment by sxa** [comment]
No this was not intentional so this should NOT have been merged

**Comment by karianna** [comment]
> No this was not intentional so this should NOT have been merged

Itchy trigger figure - my apologies!

**Pull request merged**
