### PR TITLE
winPB: Update OpenSSL 1.1.1g to 1.1.1h

### PR DESCRIPTION
**Pull request by Willsparker**
ref: #1578 

I just ran `sed -i -e 's/1.1.1g/1.1.1h/g' main.yml` and updated the checksum :-) 
Testing on VPC: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/884/

### CODE REVIEW

**Review by gdams — APPROVED** [review]
LGTM - subject to playbook tests passing

**Comment by Willsparker** [comment]
Rerun of VPC : https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/885/

**Review by sxa — COMMENTED** [review]
Nit: Can you adjust the commit message so the L in OpenSSL is capitalized

**Comment by Willsparker** [comment]
Changes the commit message and title.
The VPC run passed with the playbook - the build failed because it was looking for the old version of OpenSSL, a PR will be in for that once I get OpenSSL on the softlayer windows machines

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/886/ - The VPC run that tested both this PR and the build PR (2122) passed :-) Merging

**Pull request merged**
