### PR TITLE
unixPB: Add fontconfig to DockerStatic Dockerfiles

### PR DESCRIPTION
**Pull request by sxa**
Fixes https://github.com/AdoptOpenJDK/openjdk-tests/issues/2357 (Once deployed to all existing systems)

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by sxa** [comment]
This has been deployed on the `test-docker` machines other than [test-docker-fedora33-armv8-1](https://ci.adoptopenjdk.net/computer/test-docker-fedora33-armv8-1/) which seems to have a broken package manager so I've just disabled it (It's on a host which is due to be decomissioned soon anyway)
```
for CONTAINER in `docker ps | awk '{print$NF}' | grep ^f33`; do docker exec $CONTAINER dnf -y install fontconfig; done
for CONTAINER in `docker ps | awk '{print$NF}' | grep ^U`; do docker exec $CONTAINER apt-get -y install fontconfig; done
```

**Comment by sxa** [comment]
Apparently the check failure on macos is a known issue with gdams has raised with GitHub

**Review by lumpfish — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
I suggest the remainder of that checklist be done in a follow-up PR so that we can resolve the many test failures on the merge of the changes currently in this PR.

**Comment by sxa** [comment]
> I suggest the remainder of that checklist be done in a follow-up PR so that we can resolve the many test failures on the merge of the changes currently in this PR.

@smlambert  If by checklist you mean the checkboxes in the description they are not appropriate for this PR. However based on the comment above at https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/2130#issuecomment-819718651 it should already have been deployed to most of the machines so if there's something not working let me know (in which case I want to check there's not an additional requirement before merging this!)

**Comment by sxa** [comment]
Was missing from a couple of the images on that host - fixed and will merge (Docker/Alpine issue seems to be a docker problem unrelated to this)

**Pull request merged**
