### PR TITLE
unixPB: Add gcc9 for Dragonwell

### PR DESCRIPTION
**Pull request by sxa**
Signed-off-by: Stewart X Addison <sxa@redhat.com>

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] FAQ.md updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) - ~~[VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/997/) / [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/164/)~~ [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1037/) / [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/189/) - [Final VPC on all three CentOS](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1044/)
- [ ] inventory changes, ensure bastillion is updated accordingly

### CODE REVIEW

**Comment by joeyleeeeeee97** [comment]
@sxa  Thanks.

**Comment by joeyleeeeeee97** [comment]
Now I am testing with joeylee97/dragonwell_centos7_gcc9_build_image.
The dockerfile is 
```
FROM adoptopenjdk/centos7_build_image

RUN yum update -y
RUN yum groupinstall "Development Tools" -y
RUN yum install wget -y
RUN curl -O https://ftp.gnu.org/gnu/gcc/gcc-9.2.0/gcc-9.2.0.tar.gz
RUN tar xzf gcc-9.2.0.tar.gz
WORKDIR /gcc-9.2.0
RUN ./contrib/download_prerequisites
WORKDIR /
RUN mkdir gcc-build
WORKDIR /gcc-build
RUN ../gcc-9.2.0/configure                           \
    --enable-shared                                  \
    --enable-threads=posix                           \
    --enable-__cxa_atexit                            \
    --enable-clocale=gnu                             \
    --disable-multilib                               \
    --enable-languages=all                           \
    --prefix=/usr/local/gcc-9.2.0/
RUN make -j 4
```

**Comment by sxa** [comment]
> @sxa Thanks.
> Do we need to sync with openjdk-build/build-farm/platform-specific-configurations/linux.sh?
> like
> 
> ```
> if [ -r /usr/local/gcc/bin/gcc-9.3.0/bin/gcc ]; then
>   export PATH=/usr/local/gcc/bin/gcc-9.3.0/bin:$PATH
>   [ -r /usr/local/gcc/bin/gcc-9.2.0 ] && export CC=/usr/local/gcc/bin/gcc-9.2.0
>   [ -r /usr/local/gcc/bin/g++-9.2.0 ] && export CXX=/usr/local/gcc/bin/g++-9.2.0
>   export LD_LIBRARY_PATH=/usr/local/gcc/lib64:/usr/local/gcc/lib
> elif [ -r /usr/local/gcc/bin/gcc-7.5 ]; then
>   export PATH=/usr/local/gcc/bin:$PATH
>   [ -r /usr/local/gcc/bin/gcc-7.5 ] && export CC=/usr/local/gcc/bin/gcc-7.5
>   [ -r /usr/local/gcc/bin/g++-7.5 ] && export CXX=/usr/local/gcc/bin/g++-7.5
>   export LD_LIBRARY_PATH=/usr/local/gcc/lib64:/usr/local/gcc/lib
> elif [ -r /usr/bin/gcc-7 ]; then
>   [ -r /usr/bin/gcc-7 ] && export CC=/usr/bin/gcc-7
>   [ -r /usr/bin/g++-7 ] && export CXX=/usr/bin/g++-7
> fi
> ```
> 
> Also, could we publish it to adopt image registry?

It will to go live, but so far I've been unable to build successfully with the new gcc level

**Comment by joeyleeeeeee97** [comment]
> > @sxa Thanks.
> > Do we need to sync with openjdk-build/build-farm/platform-specific-configurations/linux.sh?
> > like
> > ```
> > if [ -r /usr/local/gcc/bin/gcc-9.3.0/bin/gcc ]; then
> >   export PATH=/usr/local/gcc/bin/gcc-9.3.0/bin:$PATH
> >   [ -r /usr/local/gcc/bin/gcc-9.2.0 ] && export CC=/usr/local/gcc/bin/gcc-9.2.0
> >   [ -r /usr/local/gcc/bin/g++-9.2.0 ] && export CXX=/usr/local/gcc/bin/g++-9.2.0
> >   export LD_LIBRARY_PATH=/usr/local/gcc/lib64:/usr/local/gcc/lib
> > elif [ -r /usr/local/gcc/bin/gcc-7.5 ]; then
> >   export PATH=/usr/local/gcc/bin:$PATH
> >   [ -r /usr/local/gcc/bin/gcc-7.5 ] && export CC=/usr/local/gcc/bin/gcc-7.5
> >   [ -r /usr/local/gcc/bin/g++-7.5 ] && export CXX=/usr/local/gcc/bin/g++-7.5
> >   export LD_LIBRARY_PATH=/usr/local/gcc/lib64:/usr/local/gcc/lib
> > elif [ -r /usr/bin/gcc-7 ]; then
> >   [ -r /usr/bin/gcc-7 ] && export CC=/usr/bin/gcc-7
> >   [ -r /usr/bin/g++-7 ] && export CXX=/usr/bin/g++-7
> > fi
> > ```
> > 
> > 
> > Also, could we publish it to adopt image registry?
> 
> It will to go live, but so far I've been unable to build successfully with the new gcc level

We did some changes including: 
https://github.com/alibaba/dragonwell11/commit/9d0ad338f3b65f6d0c3ae7ba5c4811200cf84ade
https://github.com/alibaba/dragonwell11/commit/1e5ace979799a10e24e08ae0a65b1c68c6fdcc17

**Comment by karianna** [comment]
Hmmmm Mac Os X brew running on a solaris node?

**Comment by sxa** [comment]
> Hmmmm Mac Os X brew running on a solaris node?

Sorry - what's that comment in relation to?

**Comment by karianna** [comment]
The Vagrant Playbook checker failed.

**Comment by sxa** [comment]
> The Vagrant Playbook checker failed.

Not sure why - this doesn't affect Solaris or macos, but the brew thing is from the check defined in https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/.github/workflows/build_vagrant.yml

**Comment by karianna** [comment]
> > The Vagrant Playbook checker failed.
> 
> Not sure why - this doesn't affect Solaris or macos, but the brew thing is from the check defined in https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/.github/workflows/build_vagrant.yml

This is actually fixed, you just need to rebase.

**Comment by sxa** [comment]
Solaris check now passing @karianna

**Review by karianna — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
This seems to have worked based on running it on a real machine outside a docker container: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-dragonwell/157/console

**Comment by sxa** [comment]
I'm not entirely sure why, but every time I use GCC9 on aarch64 to compile dragonwell (started with 9.3, then moved to 9.2) I get compilation failures starting with:
```CalleeWork(JNIEnv*, jobject, jint, jlong, jfloat, jdouble, jstring)’:
./test/hotspot/jtreg/compiler/calls/common/libCallsNative.c:44:22: error: base operand of ‘->’ has non-pointer type ‘JNIEnv’ {aka ‘JNIEnv_’}
   44 |   jclass cls = (*env)->GetObjectClass(env, self);
      |                      ^~
```
and failures in in `check_code.o` and `AccessController.o`. No such problems with 7.5.
Adding this info here so I can return to it on Monday

**Pull request merged**
