### PR TITLE
UnixPB: Install docker for RHEL/CentOS PPC64le/s390x

### PR DESCRIPTION
**Pull request by Willsparker**
Fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/725#issuecomment-690984024 

Changes include:
  - Removing the CentOS specific portions of the code and just adding ` or ansible_distribution == "CentOS"` to the RedHat tasks, as the CentOS section was just repeats of the RedHat Code.
  - Carry out the same steps of RHEL7/ppc64le on CentOS7, that were added in in #1460  
  - Support RHEL/CentOS7 s390x for docker, in the same format as the x86_64 docker is installed.
  - Add S390x to the SLES12 install docker task as on the `test-marist-sles12-s390x-1` machine, the `docker` package is in the `@system` repository.

### CODE REVIEW

**Comment by Willsparker** [comment]
Testing it doesn't break x64 here: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/874/
Unfortunately I can't test the specific platforms that this PR is directly affecting with either `VPC` or `QPC` as neither of them support those platforms.

**Comment by Willsparker** [comment]
Fixes: #725

**Review by aahlenst — APPROVED** [review]

**Comment by Haroon-Khel** [comment]
The additions look fine but like you mentioned the qpc doesnt support centos 7 on ppc or s390x. This does give me a reason to add these platforms to the qpc though

**Review by jdekonin — COMMENTED** [review]
Can you squash your commits and redo the comment to remove SLES?

**Comment by Willsparker** [comment]
Uhhh... I'm sort of in the middle of git rebase hell, I've managed to confuse myself a bit with this branch :facepalm:

**Pull request merged**
