### PR TITLE
Aix pb v2

### PR DESCRIPTION
**Pull request by aixtools**
This is the development path of AIX Playbook Version 2 #1582 

I am trying to give it a much better `ansible` look & feel - so comments from ansible experts re: structure is very very much appreciated.

### CODE REVIEW

**Comment by aixtools** [comment]
FYI: the CI checks failing do not (all) seem to be related to this PR.

**Comment by karianna** [comment]
@aixtools Looks like the linter warnings are legitimate (for the coding stds the infra team has put on this repo). Maybe worth discussing on the Slack channel if you think those restrictions need changing.

**Comment by aixtools** [comment]
Not saying they are not legitimate - but 'frustrating' if they are being caused by nothing "you" (that is me in third person) you have even looked at.

**Comment by Willsparker** [comment]
Couple other yamlint errors: 
```

./playbooks/aix/oss/tasks/main.yml
  3:1       error    too many blank lines (1 > 0)  (empty-lines)

./playbooks/aix/fs/tasks/main.yml
  3:1       error    too many blank lines (1 > 0)  (empty-lines)

./playbooks/aix/verify/tasks/main.yml
  3:1       error    too many blank lines (1 > 0)  (empty-lines)

./playbooks/aix/users/tasks/main.yml
  3:1       error    too many blank lines (1 > 0)  (empty-lines)
```

**Comment by aixtools** [comment]
Closing this - to quiet the CI cycles - I shall continue to push to the PR and reopen (from time to time) to update current status.

**Comment by aixtools** [comment]
Still - closed - to keep CI quiet - Ansible test environment setup, now
some more in-depth Ansible learning. WIP - continues.

**Pull request closed without merging**
