### PR TITLE
winPB: Update OpenSSL to 1.1.1i and streamline updates

### PR DESCRIPTION
**Pull request by sxa**
Draft while undergoing testing 

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] FAQ.md updated if appropriate
- [x] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] inventory changes, ensure bastillion is updated accordingly

### CODE REVIEW

**Comment by karianna** [comment]
looks good but your linter doesn't like you :-)

**Comment by sxa** [comment]
> looks good but your linter doesn't like you :-)

The role didn't like me either - for some reason it doesn't like the checksum being a variable so I'm backing that out unti lsomeone who has more time looks at fixing it but at leasdt the docs are in there now :-)

**Comment by sxa** [comment]
Linter issues resolved - verifying on [build-ibmcloud-win2012r2-x64-2](https://ci.adoptopenjdk.net/computer/build-ibmcloud-win2012r2-x64-2/) through AWX then will set ready for review before deploying elsewhere

**Comment by sxa** [comment]
Seems to be running through ok on AWX - final validation at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/959/ along with the openjdk-build change

**Review by Willsparker — APPROVED** [review]
LGTM, on the condition it passes VPC - the change to using a variable is much appreciated :sweat_smile:

**Comment by Willsparker** [comment]
ref: #1752

**Comment by sxa** [comment]
JDK8 J9 build with VS2013 looks ok, so I'd hope the others are good too.

There was one glitch during the playbook installation but this looks like a connection glitch to the machine (as you can see below it happened about a second after attempting the connection, so assumed to be unrelated to the playbook).

```
21:55:44 TASK [Download OpenSSL-1.1.1i] *************************************************
21:56:05 [WARNING]: ERROR DURING WINRM SEND INPUT - attempting to recover:
21:56:05 WinRMOperationTimeoutError
21:56:19 changed: [127.0.0.1]
21:56:19 
```

**Comment by Willsparker** [comment]
Can't say I've ever seen that connection drop issue before! Curious. But yeah, fine with me if it worked with JDK8/J9_VS2013, then if it didn't work with any other platform, it wouldn't be an issue with the playbook, I don't think :-)

**Pull request merged**
