### PR TITLE
inventory: add m1 build macOS machines + playbook support for m1

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by Willsparker** [comment]
Running VPC to make sure the changes to `adoptopenjdk_install` work: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1132/

**Comment by Willsparker** [comment]
Could you possibly remove the `brew cask --uninstall adoptopenjdk8` line from the macos (or whatever else may need to be done to fix the GitHub check). That can then test that the macOS specific stuff works, as I have no means of testing it otherwise.

The Unix side of things seem okay: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1132/OS=Debian8,label=vagrant/console

**Comment by gdams** [comment]
> Could you possibly remove the brew cask --uninstall adoptopenjdk8 line from the macos (or whatever else may need to be done to fix the GitHub check).

I double checked and the github env is meant to have adoptopenjdk8 so this is an upstream issue on their end. I'll raise a bug at GitHub

**Review by Willsparker — APPROVED** [review]
In that case, LGTM. I'm trusting you, that the macOS stuff works :sweat_smile:

**Pull request merged**
