### PR TITLE
github: add label bot to help with triaging

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by Willsparker — COMMENTED** [review]
Aren't `.yml` files meant to have newline characters at the end?

**Comment by gdams** [comment]
@Willsparker not required

**Review by Willsparker — APPROVED** [review]
LGTM

**Comment by Willsparker** [comment]
Seems to be working in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1999 :+1: cool

**Pull request merged**
