### PR TITLE
inventory: Replace build-macstadium-macos1010-x64-1 with build-macstadium-macos10104-x64-3

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1290

### CODE REVIEW

**Comment by gdams** [comment]
jenkins link: https://ci.adoptopenjdk.net/computer/build-macstadium-macos1014-x64-3/

**Review by sxa — COMMENTED** [review]
Could you update the commit message to this please?
`inventory: Replace build-macstadium-macos1010-x64-1 with build-macstadium-macos10104-x64-3`

**Comment by gdams** [comment]
> Could you update the commit message to this please?

@sxa updated

**Review by sxa — APPROVED** [review]
LGTM

**Pull request merged**
