### PR TITLE
ansible: Remove deprecation warnings regarding version_compare

### PR DESCRIPTION
**Pull request by sxa555**
Signed-off-by: Stewart Addison <sxa@uk.ibm.com>

### CODE REVIEW

**Comment by sxa555** [comment]
Seems ok - now ready for approval

**Comment by jdekonin** [comment]
What version will this be compatible with?  What version of AWX does Adopt use?

**Comment by sxa555** [comment]
It's based on ansible 2.4.0.0 - haven't explicitly checked with that version yet though.

**Comment by karianna** [comment]
> It's based on ansible 2.4.0.0 - haven't explicitly checked with that version yet though.

What level is our linter set at? If it's 2.4.x then we can land this...

**Comment by sxa555** [comment]
I'm not sure it has a specific version defined, although the fact the checks haven't tripped up suggest it's ok unless you have any specific concerns I'm missing @karianna

**Pull request merged**
