### PR TITLE
aixPB: name debug: tasks to satisfy linter

### PR DESCRIPTION
**Pull request by aixtools**
Fix a lot of noise in future PR's - AIX related

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by aixtools** [comment]
Interesting that the bot only sees this as exclusive to AIX 😛

**Comment by aixtools** [comment]
Closing this for now - the linter keeps going deeper - finding more unnamed blocks and I no longer feel comfortable making the linter happy.

**Comment by aixtools** [comment]
Reopening - after removing the UNIX related playbooks.

Also renamed the old AIX playbooks - so that the linter will (should!) no longer consider their code relevant.

**Comment by aixtools** [comment]
p.s. not trying to resolve the UNIX ansible errors - so the linter red X will still be there.

**Review by Willsparker — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
> p.s. not trying to resolve the UNIX ansible errors - so the linter red X will still be there.

Thanks for this - the UNIX ones are being done separately under https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/2051

**Review by sxa — APPROVED** [review]
Looks good - I've merged (conflicted with the xlc16 PR, unsurprisingly) and Michael has double checked it.

**Pull request merged**
