### PR TITLE
github: remove CentOS6 PR check

### PR DESCRIPTION
**Pull request by sxa**
To avoid confusion and not put off potential contributors we should remove this check for now until https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1745 is resolved.

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] FAQ.md updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] inventory changes, ensure bastillion is updated accordingly

### CODE REVIEW

**Comment by gdams** [comment]
My only concern with this is that it's what is used to update the docker images for the builds.

**Comment by sxa** [comment]
> My only concern with this is that it's what is used to update the docker images for the builds.

There looks to be actions in there associated with PRs and pushes - is the push executed when it's merged? [NOTE: Original PR had the wrong but comented out - have adjusted to leave it on push] Otherwise aren't we pushing and updating the image on every PR creation regardless of whether it's approved?

Either way, presumably at the moment it's unable to update so is fundamentally non-functional right now and only leading to confusion?

**Comment by sxa** [comment]
> wasn't there a proposed fix coming from Will?

I believe you're referring to https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1765/files which has already been merged and does not appear to have fixed the issue in the github checks.

@Willsparker are you still looking at a further fix?

**Comment by Willsparker** [comment]
That only solves part of the problem. See https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1745
The same sed change needs to be done on the SCL repo - but due to that being added in the playbook, it needs to be an ansible task too.

**Comment by karianna** [comment]
@Willsparker Is that something which can be resolved soon or should we land this instead?

**Comment by Willsparker** [comment]
I'll have it done by today :-)

**Comment by Willsparker** [comment]
As of #1780, the CentOS6 PR check works. ([VPC](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/977/OS=CentOS6,label=vagrant/console) also shows that the C6 playbook is working on a vagrant VM, too). Closing this as it's unnecessary now :-)

**Pull request closed without merging**
