### PR TITLE
Vagrant: Add warning in docs about starting Windows VM with too little memory

### PR DESCRIPTION
**Pull request by Willsparker**
This is a problem I came across when setting up a new laptop. I don't think we should reduce the memory of the Windows Vagrantfile, otherwise it can significantly increase the time taken to execute `VPC.sh` on it- but a warning should probably be put in to the docs, in case the user doesn't have enough available memory and is wondering why their VM is going to the aborted state straight away.

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Review by sxa — COMMENTED** [review]
Can we trap this situation in the script (perhaps when a connection error occurs) and say something like "If your machine has 8GB or less of RAM, try editing this line in Vagrantfile.Win2012"

If it's possible to detect that situation (e.g. from a log file, or even just "testing windows and host has <=8Gb RAM) then perhaps we can improve the message further.

**Comment by Willsparker** [comment]
>  If it's possible to detect that situation (e.g. from a log file, or even just "testing windows and host has <=8Gb RAM) then perhaps we can improve the message further.

I do quite like that idea. It can be put into the `checkVars` function in _vagrantPlaybookCheck.sh_ . However, in terms of warning people if they're just using the Vagrantfile, not the script, I don't think there's any way to warn them except in our docs - I tried using `config.vm.post_up_message` ( https://www.vagrantup.com/docs/vagrantfile/machine_settings#config-vm-post_up_message ), however that doesn't print a message if `vagrant up` fails :/

**Review by sxa — APPROVED** [review]

**Comment by Willsparker** [comment]
I know you both have approved beforehand, but I didn't want to add a commit after approval and then merge right away

**Comment by sxa** [comment]
Since it's just that extra comment that's not a problem - we can merge :-)

**Comment by Willsparker** [comment]
Cool, thanks :-)

**Pull request merged**
