### PR TITLE
[WIP] ansible: Reference correct default PATH to 7-zip when extracting mingw

### PR DESCRIPTION
**Pull request by sxa555**
Signed-off-by: Stewart Addison <sxa@uk.ibm.com>

WIP as needs to be tested.
Alternative solution is to adjust the 7-Zip role to install to `C:\7-Zip` (probably the better solution ... This is really just a placeholder to ensure someone comes up with a solution!

### CODE REVIEW

**Comment by HusainYusufali** [comment]
I will be changing the 7-Zip role to install 7-Zip into the `C:\7-Zip` directory instead of modifying mingw

**Comment by HusainYusufali** [comment]
Pull request #653 has changed the 7-Zip role to make the install directory `C:\7-Zip`

**Comment by karianna** [comment]
#653 has landed, does this PR now need to change?

**Comment by sxa555** [comment]
Yep just needs to be canceled :-)

**Pull request closed without merging**
