### PR TITLE
Changed Protobuf configure options

### PR DESCRIPTION
**Pull request by cwesMills**
Changed configure options for Protobuf to make Protobuf more optimized.

Signed-off-by: Colton Mills <millscolt3@gmail.com>

### CODE REVIEW

**Comment by sxa555** [comment]
Is protobuf included in our distribution? If not, presumably this only affects runtime (i.e. when running tests)?

**Comment by cwesMills** [comment]
@dmitry-ten could you please answer the above question.

**Comment by sxa555** [comment]
Ping @dmitry-ten

**Comment by karianna** [comment]
> Sorry, haven't seen this PR before. I thought the previous ping referred to a different PR.
> We've been running all tests with statically linked protobuf for a while now, haven't seen anything break. I thought protobuf on all affected machines was already rebuilt.

I suggest that we land this when @dmitry-ten is online to help support if things break :-)

What day/time suits?

**Comment by dmitry-ten** [comment]
Tuesday-Friday morning should be fine, just ping me when this happens.
Evening might work, but I'm in Moscow rn, so time difference makes it more complicated.

**Comment by karianna** [comment]
> Tuesday-Friday morning EST should be fine, just ping me when this happens.
> Actually, since you seem to be in UK, morning uk time should also work, since I'm in Moscow rn.

Sorry to reply to this so late.  Are you on our adoptopenjdk.net/slack.html slack? it'll be easier to co-ordinate a time there.

**Comment by dmitry-ten** [comment]
Yes, I am on that slack channel.

**Comment by sxa555** [comment]
@dmitry-ten @karianna Any progress on this?

**Comment by jdekonin** [comment]
@dchopra001 confirmed the setup for Eclipse/OpenJ9 machines, including an add for the removal of any existing package.  I think this PR should be closed and I can open a new one with all the required changes, which are slightly more than what is here.

**Pull request closed without merging**
