### PR TITLE
unixPB: Update Checksum for Docker CentOS/RHEL7 x64

### PR DESCRIPTION
**Pull request by Willsparker**
Ref: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1005/OS=CentOS6,label=vagrant/console

Docker repo checksum is wrong.

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) : In progress: [VPC](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1008/)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by sxa — APPROVED** [review]
I'll let this through for now but going forward we should definitely aim to find a better way of validatin these checksums (I'm guessing you just downloaded it and added whatever the checksum was?)

**Review by karianna — APPROVED** [review]
lgtm

**Comment by karianna** [comment]
Do we have a fix for Centos 6 failing on PR builds?

**Comment by Willsparker** [comment]
> I'll let this through for now but going forward we should definitely aim to find a better way of validatin these checksums (I'm guessing you just downloaded it and added whatever the checksum was?)

Yeah, using `sha256sum`

> Do we have a fix for Centos 6 failing on PR builds?

Currently investigating it in #1877 :-)

**Pull request merged**
