### PR TITLE
WIP: Install MinGW-W64 on Windows

### PR DESCRIPTION
**Pull request by vsebe**
- install 7zip
- install MinGW from a 7zip package

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
OpenJ9 requires MinGW-W64 8 for JDK11 and up with MSVS 2017. v8.x is not available yet for cygwin.

**Comment by vsebe** [comment]
@sxa555 fyi

**Comment by vsebe** [comment]
@jdekonin fyi

**Comment by vsebe** [comment]
@sxa555 - I have broken it down in two playbooks as required.
Please note that I haven't yet test it (no ansible tower access yet), hence the "WIP" prefix.

**Comment by vsebe** [comment]
This PR is for VS 2017. 
For older toolchain versions - VS2010, VS2013- the mingw package available with cygwing works fine.
The openjdk10_openj9_build_x86-64_windows uses VS2013: `--with-toolchain-version=2013 `

```
Running ./configure with arguments ' --with-version-pre=adoptopenjdk --with-version-string=10.0.2+13  --with-boot-jdk=/cygdrive/c/openjdk/jdk9 --with-freetype-src=/cygdrive/c/openjdk/freetype-2.5.3 --with-toolchain-version=2013 --with-freemarker-jar=/cygdrive/c/openjdk/freemarker.jar --disable-ccache --with-milestone=fcs'

```
`x86_64-w64-mingw32-g++` ([mingw64-x86_64-gcc-g++](https://cygwin.com/packages/x86_64/mingw64-x86_64-gcc-g++/mingw64-x86_64-gcc-g++-5.4.0-3) package) should have been installed with cygwin and be available in `/usr/bin` (Linux path) or `C:\cygwin64\bin` (Windows path) .

**Comment by karianna** [comment]
@vsebe Thanks!  That's a great write up - I'll split it into a different issue

**Pull request merged**
