### PR TITLE
unixPB: disable macOS keychain timeout

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2120

### CODE REVIEW

**Review by Willsparker — APPROVED** [review]
LGTM

**Review by Willsparker — CHANGES_REQUESTED** [review]
Ah, actually, isn't it a security concern to have it open all the time? Can we close it signing the cert?

**Comment by gdams** [comment]
All of our other machines have this setting already. The keychain remains unlocked for the current SSH session only

**Review by Willsparker — APPROVED** [review]
LGTM

**Pull request merged**
