### PR TITLE
winPB: Retrieve MSVS_2017/19 installers from ci.adoptopenjdk.net

### PR DESCRIPTION
**Pull request by Willsparker**
Ref: #1545 , https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1517#pullrequestreview-475402407
Fixes: #1546 

Retrieve the MSVS installers from `ci.adoptopenjdk.net/userContent/winansible/MSVS_installers/`. This is to stop the installer updates that change the checksum (thereby meaning I have to PR them to change them every time). AFAIK, the latest updates of MSVS can still be installed with old versions of the installer, so this shouldn't affect the installation of MSVS itself (and therefore won't affect builds). This way we're also able to keep the checksum checks :-)

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by Willsparker** [comment]
Oh, I forgot to mention, I put this through `VPC`, and the playbook seems good.
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/880/OS=Win2012,label=vagrant/

I'm not quite sure why the build failed tho - I'm rerunning just to double check. https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/881/

**Review by sxa — COMMENTED** [review]
Typo in "retrieve"

**Comment by gdams** [comment]
Are there any legal issues with hosting the visual studio installers on our own web server?

**Comment by Willsparker** [comment]
Files have been removed from the public server, so this PRs been put into draft until we can find a secure place to put them :-)

**Comment by aahlenst** [comment]
One possible solution is to put those into Artifactory into a private repo that can only be accessed by authenticated users. Works great with Ansible.

**Comment by gdams** [comment]
@aahlenst we want to avoid that because it would mean that other people would not be able to use our playbooks anymore.

**Comment by karianna** [comment]
merge conflicts.

**Comment by Willsparker** [comment]
Conflicts resolved - It was due to the workaround PR that removes the checksum.
From what I can see, if we can't legally redistribute the installer, we're going to just deal with the often changing checksum, or remove it, if we want to keep the playbooks working for everyone.

**Comment by karianna** [comment]
> Conflicts resolved - It was due to the workaround PR that removes the checksum.
> From what I can see, if we can't legally redistribute the installer, we're going to just deal with the often changing checksum, or remove it, if we want to keep the playbooks working for everyone.

Opportunity to write a bot or GitHub Action to create PR like dependabot?

**Comment by sxa** [comment]
Closing as we are not going to redistribute this way

**Pull request closed without merging**
