### PR TITLE
Delete ubuntu-api.yml

### PR DESCRIPTION
**Pull request by gdams**
not needed anymore because we migrated to openshift

### CODE REVIEW

**Comment by gdams** [comment]
@jdekonin the sooner you merge it the sooner you can delete the branch then

**Comment by karianna** [comment]
> @jdekonin the sooner you merge it the sooner you can delete the branch then

@gdams I don't think that's the point - we need to be able to audit where PRs come from...

**Comment by gdams** [comment]
you still can? when the commit gets merged it is still associated to my PR?

**Comment by sxa555** [comment]
Approving on the basis that this is now being done through the standard nodejs docker images pointing at the `openjdk-api` repository to start the API.

**Pull request merged**
