### PR TITLE
unixPB enable core dumps on macOS

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] FAQ.md updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] inventory changes, ensure bastillion is updated accordingly

fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1282

Grinder before change: https://ci.adoptopenjdk.net/job/Grinder/5835/tapResults/
Grinder after change: https://ci.adoptopenjdk.net/job/Grinder/5837/tapResults/

### CODE REVIEW

**Comment by karianna** [comment]
```
TASK [Common : Install Build Tool Casks] ***************************************
failed: [localhost] (item=adoptopenjdk10) => {"ansible_loop_var": "item", "changed": false, "item": "adoptopenjdk10", "msg": "Updating Homebrew...\nError: Calling brew cask install is disabled! Use brew install [--cask] instead."}
failed: [localhost] (item=packages) => {"ansible_loop_var": "item", "changed": false, "item": "packages", "msg": "Error: Calling brew cask install is disabled! Use brew install [--cask] instead."}
```

**Review by sxa — APPROVED** [review]

**Review by sxa — CHANGES_REQUESTED** [review]
Isn't the `ulimit` here being run as a one off during the ansible session as opposed to being permanent?

**Comment by gdams** [comment]
> Isn't the ulimit here being run as a one off during the ansible session as opposed to being permanent?

@sxa it's a one-off. It seems to be set before running the tests but if it's not set correctly before creating the `/cores` directory we run into permission issues

**Comment by sxa** [comment]
> > Isn't the ulimit here being run as a one off during the ansible session as opposed to being permanent?
> 
> @sxa it's a one-off. It seems to be set before running the tests but if it's not set correctly before creating the `/cores` directory we run into permission issues

I don't understand how that can be the case - which permission issues are related to the `ulimit`? Can you give specifics as I'd rather not have unecessary things in there that could cause confusion (So if it really is needed the reason should be documented in a comment). We're not generating any cores in the playbook (Hopefully!) so I can't see how the ulimit would affect the creation of a directory.

**Comment by sxa** [comment]
Not quite sure yet what it's complaining about - ansible-lint does not object in the same way when run on my local machine.

**Comment by andrew-m-leonard** [comment]
I'm sure I ran the failing testcase earlier today on test-macstadium-macos1014-x64-1 after I changed the /cores permissions to 0774, and it succeeded with ulimit 0, I didn't change it...

**Comment by gdams** [comment]
just tested it again, confirmed that I don't need the ulimit command. Updating the PR

**Review by sxa — APPROVED** [review]

**Pull request merged**
