### PR TITLE
fix playbooks on macOS

### PR DESCRIPTION
**Pull request by gdams**
a few extra skips were required to make the playbook fully run on macOS

### CODE REVIEW

**Comment by gdams** [comment]
@sxa added a prefix,

Using the API would get difficult on macOS, especially as the bundle needs to be notarized, sticking with the casks is by far the easiest approach here.

**Comment by sxa** [comment]
> Using the API would get difficult on macOS, especially as the bundle needs to be notarized

Can you clarify what is it that doesn't work for a boot JDK here if it's not notarized? And what else would be difficult?

**Comment by gdams** [comment]
gatekeeper would not allow the binary to be executed which would cause issues.

**Comment by sxa** [comment]
> gatekeeper would not allow the binary to be executed which would cause issues.

@gdams Can you clarify/document from a naive non-mac user perspective what these issues would be? My understanding is that it's possible to extract into `/usr/local` as an adminstrator and have java execute as a normal user from there.

**Comment by gdams** [comment]
@sxa for starters the macos bundles have to be extracted to:

`/Library/Java/JavaVirtualMachines/adoptopenjdk-<version>.jdk/` in order for the system to correctly identify them.

On a Catalina machine or above any bundle that isn't notarized will cause the following error:

image

essentially as soon as the java process is created it gets destroyed by gatekeeper.

Using homebrew is definitely the way to go here, it also allows us to update the openjdk versions easily.

**Comment by aahlenst** [comment]
As a side note only: If you download via curl or wget, the Gatekeeper attributes aren't added. You can move the extracted tarball to `/Library/Java/JavaVirtualMachines` and launch java. Gatekeeper etc. only kicks in if you use Apple tools like Safari that add the quarantine attributes. Or Homebrew, which does that, too 🙄 

Ubuntu 20.04 ISO downloaded via Safari:

```
$ xattr ubuntu-20.04-live-server-amd64.iso
com.apple.lastuseddate#PS
com.apple.macl
com.apple.metadata:kMDItemDownloadedDate
com.apple.metadata:kMDItemWhereFroms
com.apple.quarantine
```

AdoptOpenJDK 14 downloaded via wget:

```
$ xattr OpenJDK14U-jdk_x64_mac_hotspot_14.0.1_7.tar.gz
```

**Comment by sxa** [comment]
Consistent with what @aahlenst is suggesting I have confirmed with someone on Catalina that they are able to extract the tarball into `/usr/local` on their machine and have it run as a normal user, so I'm not sure what the inmplications of the extraction location you mention or the Gatekeeper error is with respect to extracting the tarball, but that does not appear to be correct.

**Comment by gdams** [comment]
okay @sxa if it works then I have not personal objections. As mentioned before I would suggest extracting them to the correct location `/Library/Java/JavaVirtualMachines`

There will be some script changes needed to support this as the macOS tarballs are in the form of a bundle as well. Let's get this PR in and then we can work out the best approach

**Comment by sxa** [comment]
As discussed on our call last week if the changes go in to make the extraction consistent with the other platforms (I'm ok with the location you suggest!) then I'll approve and merge this.

**Comment by karianna** [comment]
@gdams also merge conflict now

**Pull request closed without merging**
