### PR TITLE
 add aarch64and armv7 docker support

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Comment by sxa555** [comment]
I'm wondering if we could just change this conditional to "Not arm32" now (assuming it won't work on arm32 ... If it does we should just remove the architecture conditional altogether!)

**Comment by gdams** [comment]
@sxa555 added the armv7 docker repo too.

**Comment by sxa555** [comment]
(Haven't got round to this yet but still near the top of my list!)

**Comment by gdams** [comment]
@sxa555 I've already confirmed that arm32 works. There is no need for you to run your test

**Comment by sxa555** [comment]
Looks good

**Pull request merged**
