### PR TITLE
ansible: Create Windows JDK7 link as jdk-7 instead of jdk7

### PR DESCRIPTION
**Pull request by sxa**
I would like to obtain explicit approval from EVERYONE on the reviewers list. Can I ask no-one else other than me to merge please (which is the default policy for the openjdk-infrastructure repo anyway, but let's make sure no-one misses it for this one ;-)

The link in `C:\openjdk` for the Java 7 boot JDK is created as `jdk7` instead of `jdk-7`. This is inconsistent with all other versions. The current production build machines seem to have a mix, so I'm choosing to standardise on the same as the other versions.

To all reviewers: Please let me know if this will impact you and if so when you will have mitigated it (or if you are unable to do so - in which case we would still have the option to put both in place but I'd rather avoid that)

Attempting test via [VPC](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/900/console)

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Review by AdamBrousseau — APPROVED** [review]
This is fine with me, thanks for the heads-up.

**Review by Willsparker — APPROVED** [review]
Yep, nothing against this on the condition it works in VPC. Reruns at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/902/ & https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/903/

**Review by karianna — APPROVED** [review]
LGTM, no impact as far as I can see.

**Comment by sxa** [comment]
Happy with the set of reviews I've had - merging as this matches what the two new machines we use at AdoptOpenJDK now have

**Pull request merged**
