### PR TITLE
Add scheduled job to delete marked jenkins workspaces

### PR DESCRIPTION
**Pull request by ali-ince**
This adds a new scheduled job to remove marked (`ws-cleanup` in their names) workspace folders on windows.

Assumed that Jenkins always use `workspace` folder under `jenkins` user home directory and also changed `Jenkins_User` role name to `Jenkins`.

Addresses #477.

### CODE REVIEW

**Comment by karianna** [comment]
@ali-ince travis failed linting:

```
./playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins/tasks/main.yml
11:29 warning  truthy value should be true or false(truthy)
19:81 warning  line too long (156 > 80 characters)(line-length)
21:5 error    wrong indentation: expected 6 but found 4(indentation)
22:81 warning  line too long (144 > 80 characters)(line-length)
24:5 error    wrong indentation: expected 6 but found 4(indentation)
28:14 warning  truthy value should be true or false(truthy)
28:17 error    no new line character at the end of file(new-line-at-end-of-file)
```

You only have to fix errors to get it to pass

**Comment by karianna** [comment]
@ali-ince Unfortunately travis still doesn't like it :-)

**Comment by ali-ince** [comment]
@karianna Sorry for the trouble, it took some time to get used to :)

**Comment by karianna** [comment]
No worries at all thanks for the help!!

**Pull request merged**
