### PR TITLE
 UnixPB: Remove CPAN role

### PR DESCRIPTION
**Pull request by Willsparker**
Initially bought around from @gdams comment https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1580993701028200
talking about this PR #1129

### CODE REVIEW

**Comment by Willsparker** [comment]
Just in the process of removing additional code George suggested to me, I'll put it through the job once that's in :-)

**Comment by Willsparker** [comment]
Playbook job is running through : https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/357/

**Comment by gdams** [comment]
@smlambert do we still need the perl deps? I wasn't sure if they could be ditched too??

**Comment by smlambert** [comment]
Mentioned in Slack, tests still need core perl (modules that come with standard perl install), the extra CPAN modules are no longer a prereq.  This PR looks right.

**Comment by karianna** [comment]
@Willsparker merge conflict

**Comment by Willsparker** [comment]
The Jenkins job above has completed, with most OSs succeeding - the ones that failed are due to the Vagrantfile not being there ( CentOS8, will be fixed by #1131 ) and the strange recurring bug I have with Vagrant VMs turning each other off when a playbook finishes. Removing the CPAN role doesn't affect building JDK8-J9 anyway 👍

**Pull request merged**
