### PR TITLE
unixPB: skip validating certs for devtools-2 on Centos

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] FAQ.md updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] inventory changes, ensure bastillion is updated accordingly

Fixes the current GitHub actions failure on Centos6

### CODE REVIEW

**Review by karianna — CHANGES_REQUESTED** [review]
This needs a comment as to why

**Review by Willsparker — APPROVED** [review]
LGTM, after @karianna 's suggested change

**Review by sxa — COMMENTED** [review]
Hmmmm `Docker / Centos6 (pull_request) Failing after 14m — Centos6` <<< May not have fully fixed the problem

**Review by karianna — APPROVED** [review]

**Review by karianna — CHANGES_REQUESTED** [review]
PR Builder test still fails

**Pull request closed without merging**
