### PR TITLE
WIP: Create BUILDING.md

### PR DESCRIPTION
**Pull request by gdams**
An initial draft of a supported levels table.

### CODE REVIEW

**Comment by jdekonin** [comment]
There are two other dimensions to this as well.; release and originator  There are platforms that OpenJDK lists as minimum supported and those that OpenJ9 lists as minimum supported. 

OpenJDK is published [here](https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms)
Not sure about OpenJ9, I will see if I can find something on their site and update with a url.

**Comment by karianna** [comment]
See https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms

**Comment by sxa555** [comment]
For completeness on this, there is also my initial stab at a supported platforms list at https://github.com/AdoptOpenJDK/openjdk-build/wiki/%5BWIP%5D-Minimum-OS-levels

**Comment by karianna** [comment]
Yeah this should be in the openjdk-build repo and is OK as a wiki I think.  We should mostly just reference the official OpenJDK and OpenJ9 docs for each version and inly add our extra bits for platforms that OpenJDK doesn't cover (build instruction wise)

**Comment by sxa555** [comment]
Sounds like the document I already have in there is the right place to flesh out any further detail, unless we want separate documents for build environments vs running our supplied binaries (My doc is the latter)
@gdams Where did those figures for kernel and glibc versions come from - did you just pull them from a particular OS?

**Comment by sxa555** [comment]
This can probably now be considered superceded by the combination of the compiler table in the [new Build FAQ](https://github.com/AdoptOpenJDK/openjdk-build/pull/1457) and the wiki document referenced above

**Comment by sxa555** [comment]
No further updates ... closing

**Pull request closed without merging**
