### PR TITLE
Add freemarker role for unix playbooks

### PR DESCRIPTION
**Pull request by jdekonin**
Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by bblondin** [comment]
Could we move the cleanup to the cleanup role?

**Comment by jdekonin** [comment]
Cleanup moved to cleanup role.

**Comment by jdekonin** [comment]
This is not the cause.  This adds freemarker to the /home/$jenkins_user location via ansible script.  When sourceforge was unavailable for a few days, I thought adding locally controlled version a good idea.  And better yet, since the file version never changes add it to the machine so as to not increase the time of a compile job with machine setup actions.

**Comment by karianna** [comment]
@jdekonin You're totally correct and my apologies!

**Pull request merged**
