### PR TITLE
ansible : add dragonwell bootstrap image for windows

### PR DESCRIPTION
**Pull request by joeyleeeeeee97**
##### Checklist

- [ x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] FAQ.md updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] inventory changes, ensure bastillion is updated accordingly

### CODE REVIEW

**Comment by karianna** [comment]
@joeyleeeeeee97 The YAML linter failed:

```
lint: info: yamllint on ..
lint: error: failed yamllint on ..
Error: [colons] too many spaces after colon
```

**Comment by joeyleeeeeee97** [comment]
@karianna corrected YAML format except for download URL, I haven't found a valid way to break that into multi-lines.(may introduce an extra character in the URL).
Also, appreciate it if I could get some help to verify this runs as expected as I am still struggling with using ansible to manipulate our windows server.
Thanks.

**Comment by karianna** [comment]
> @karianna corrected YAML format except for download URL, I haven't found a valid way to break that into multi-lines. (may introduce an extra character in the URL).
> Also, appreciate it if I could get some help to verify this runs as expected as I am still struggling with using ansible to manipulate our windows server.
> Thanks.

Yamllint is good now thanks

**Review by karianna — APPROVED** [review]
LGTM

**Review by gdams — APPROVED** [review]

**Pull request merged**
