### PR TITLE
improve username logic for running non-sudo tasks on mac

### PR DESCRIPTION
**Pull request by gdams**
this avoids us hard-coding the username on macOS

### CODE REVIEW

**Comment by gdams** [comment]
No it’s just that some of the Mac’s have an admin account and others have administrator, using this var allows us to auto detect it

**Comment by sxa555** [comment]
Possibly a silly question but where is the auto-detection. I see
```
        - "ansible_user: {{ ansible_user | default('***Undefined***') }}" 
```
Is it really autodetected somewhere or something we will set as a parameter for each machine?

**Comment by gdams** [comment]
`ansible_user` is a built-in ansible variable :)

**Comment by sxa555** [comment]
So the answer is "It's hard coded in the inventory file and taken from there" right?

**Comment by gdams** [comment]
No it’s got nothing to do with the inventory file, it’s essentially the equivalent of ansible running whoami. On the username that’s used to ssh to the machine before elevating to root

**Pull request merged**
