### PR TITLE
Changed Protobuf configure options

### PR DESCRIPTION
**Pull request by jdekonin**
* changed configure options for Protobuf to make Protobuf more optimized
* replacing #883

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
The is an inconsistency with functionality in what is generated when using gcc 5.5 or older; we used 7.3 because it is already on the system via playbook.

**Comment by sxa555** [comment]
Do you have the details of the inconsistency (is there an issue?) and will it mean we have to redeploy protobuf on all machines? Also can you add a comment to that effect into the playbook as it might look confusing to someone in the future.

**Comment by jdekonin** [comment]
I have no direct reference no.  But I believe the answer is that yes you would need to redeploy protobuf.   @dchopra001, can you please comment on why gcc7?

**Comment by dchopra001** [comment]
I no longer have a specific example of the issue.

In my internal testing I ran into a lot of strange linking issues. One of the steps I took to resolve them at the time was to build protobuf with gcc-7 as well. It's _possible_ that some of those were related to the particular set of machines I was using and not the gcc level itself. Also, the logic to do this in those scenarios was a lot simpler.

I suppose we can remove the gcc-7 requirement here and try to build protobuf without gcc-7 and see if everything is working (we statically link the library as well, so I guess it _should_ be okay). If we experience issues then we'll know to move up to 7 again.

**Comment by sxa555** [comment]
Thanks @dchopra001 that sounds like a good option for now to keep the playbooks simple. We haven't had any reported issues to my knowledge with the building and testing on the adoptopenjdk systems which will have been done with the default gcc on those systems. Tagging @smlambert in case she's seen anything

**Comment by smlambert** [comment]
Thanks for the tag, I am just back from travelling, I will take a closer look at recent test runs to see if anything new has appeared.

**Comment by dchopra001** [comment]
Actually @sxa555 I think it might be better if we decided to compile protobuf with gcc-7. Compiling with gcc-7 actually makes sense because protobufs are used to support JITServer in OpenJ9 and JITServer must be compiled with gcc-7 as well. I think it would be good if we kept this consistency as it can avoid problems now and into the future. Moreover, this is how we have been building on our own machines and inside Dockerfiles as well. It would be good if the build machines are setup to behave the same way. In the event that there are functional or performance issues in the future, this can be important detail.

Additionally, I recall us running into issues when protobuf was compiled with gcc 5.5 on some ubuntu 16 machines. Given the amount of issues we encountered and varying compiler levels among different machines, I think it'll be wiser if we keep the setup standard across all platforms by using gcc-7 to build on all of them.

**Comment by sxa555** [comment]
@dchopra001 I'm still nervous as it will mean inconsistencies in installation depending on whether gcc7 has been installed on the machine or not. Where are the Dockerfiles that you're referring to for the JITaaS setup? I would be interested in seeing the details of any problems, since I believe the OpenJ9 machines are set up the same as the adoptopenjdk ones and so will likely be using a version compiled with GCC 4.8 up til now.

Also @jdekonin if we're going to do this we'll probably need to add a case for `/usr/local/gcc/bin/gcc-7.4` for Linux/s390x too :-)

**Comment by dchopra001** [comment]
@sxa555 Here's the JITServer build dockerfile for x86:
https://github.com/eclipse/openj9/blob/b204b03c1861227451b05e187e3e8736ac7fa456/buildenv/docker/jdk8/x86_64/ubuntu16/jitserver/build/Dockerfile#L61-L65

**Comment by jdekonin** [comment]
Although for PR and build testing jenkins uses these docker files.
https://github.com/eclipse/openj9/tree/b204b03c1861227451b05e187e3e8736ac7fa456/buildenv/jenkins/docker-slaves/

Additional check for 7.4 added.

**Comment by dchopra001** [comment]
@mpirvu FYI

**Comment by dchopra001** [comment]
@sxa555 Are you okay with approving this change now and letting the protobuf installation happen with gcc-7?

**Comment by sxa555** [comment]
Yep

**Pull request merged**
