### PR TITLE
Added build tags to appropriate roles

### PR DESCRIPTION
**Pull request by Haroon-Khel**
Related to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/683

The tags `build_tools`, `build_tools_openj9` and `build_tools_openjfx` have been added to certain roles/tasks so that these can be skipped if creating only a test machine.

~~This is a work in progress, please do not merge yet~~

### CODE REVIEW

**Comment by Haroon-Khel** [comment]
@sxa555 This playbook has been tested on Centos 7, RHEL 7, Ubuntu 16 and 18, all x64. Its still a bit finicky on SLES 12; the playbook runs successfully, but git will not work well on the machine. This issue was present on the other distributions. but was resolved by installing libcurl-devel. I haven't found this fix to work with SLES 12.

**Comment by Haroon-Khel** [comment]
On the machines on which the playbook ran successfully, I ran a significant number of jdk8 tests using jtreg. There were some failures, but these did not differ in number than a 'control' machine (a centos 7 fyre machine on which the playbook ran without skipping any build tags)

**Comment by Willsparker** [comment]
@Haroon-Khel I'll test this locally on my machine tomorrow. I can't use `vagrantPlaybookCheck` as it will need to be modified to add an option to use these new tags :-)

**Comment by Willsparker** [comment]
Got round to testing it - when running `ansible-playbook  ... --skip-tags adoptopenjdk,jenkins,build_tools,build_tools_openJ9 ...` the playbook ran through as expected on an Ubuntu 16 x86_64 machine, and was able to test a downloaded JDK8 version (by running a modified `./pbTestScripts/testJDK.sh` script).

**Comment by Haroon-Khel** [comment]
@Willsparker @sxa555 Do you think further Java tests are required on the machines on which this playbook can run, for us to safely say these build tags are satisfactory?

**Comment by karianna** [comment]
> @Willsparker @sxa555 Do you think further Java tests are required on the machines on which this playbook can run, for us to safely say these build tags are satisfactory?
> 
> Or are jdk8 tests sufficient?

I'll call it good enough testing.

**Pull request merged**
