### PR TITLE
Add JDK12 prereqs libXi libXrandr to linux playbooks

### LINKED ISSUE #639: Add JDK12 prereqs to Ansible
Need some more header files on the build systems. These files were previously available in the OpenJDK source but from the latest JDK 12 code these files are not provided in their source, so they need to be available on the machine that is building OpenJDK.

Example failed configure output from a build on Cent6 x86-64
```
00:06:35 checking for X11/Intrinsic.h... yes
00:06:35 checking for X11/extensions/Xrandr.h... no
00:06:35 configure: error: Could not find all X11 headers (shape.h Xrender.h Xrander.h XTest.h Intrinsic.h). You might be able to fix this by running 'sudo yum install libXtst-devel libXt-devel libXrender-devel libXrandr-devel libXi-devel'.
00:06:35 configure exiting with result code 1
```

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Fixes #639

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@sxa555 for review

**Comment by karianna** [comment]
@AdamBrousseau I'm happy with this, but the old question of documenting "why we are adding these" still remain.  Can you start a comment block at the top of the `Build_Tool_Packages:` section?  Let's start boy/girl scouting this as we go.

**Comment by sxa555** [comment]
@karianna I think adding a block at the start is likely to just become a headache - IMHO we should add a (lined up) comment to the end of each line which I think will be preferable e.g.
```
  - libXrandr-devel                    # JDK12 build PR640
```

**Comment by AdamBrousseau** [comment]
Added the comments. I had this version drafted before Stewart's suggestion was made. Let me know which you prefer and I can update if necessary.

**Pull request merged**
