### PR TITLE
UnixPB: Install docker.io for Debian, Add gcc-7 to Common role for aarch64 

### PR DESCRIPTION
**Pull request by Willsparker**
ref: #1444  ; https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/46/ARCHITECTURE=arm64,label=vagrant/

For Debian10/aarch64 , `docker-ce` isn't an available package, however `docker.io` is : https://packages.debian.org/buster/arm64/docker.io/download

Running through QEMUPlaybookCheck here: https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/47/

### CODE REVIEW

**Comment by sxa** [comment]
Any reason why this needs to be specific to aarch64? If we can use `docker.io` on all architectures I'd suggest doing so

**Comment by Willsparker** [comment]
No reason other than I haven't tested other architectures yet - I know `docker-ce` at least works for Debian10 on x86_64 (looking at `VPC`) , so I'll investigate if `docker.io` works too :-)

**Comment by aahlenst** [comment]
`docker-ce` usually refers to the upstream package (see https://docs.docker.com/engine/install/debian/), `docker.io` is usually bundled with the distributions. `docker-ce` is available on significantly less platforms (amd64, armhf, arm64).

**Comment by Willsparker** [comment]
Alright, makes sense to just use `docker.io` then! Cheers

**Comment by Willsparker** [comment]
Marked the PR as a draft as I'll just add to this PR until we get a clean ARM64 run. 
In it's current state, Debian10 aarch64 doesn't install any version of gcc-7 / g++-7. This is easily rectified by just adding it to the list of packages in the `Common` role.

**Comment by Willsparker** [comment]
With the latest commit, I've moved `gcc-7` and `g++-7` to the common build tools, as the addition of it to `aarch64` means it would appear in every architecture specific list of packages, which is inefficient

**Comment by Willsparker** [comment]
> Can we remove the section on `- name: Add Docker repo for Debian x86_64` with this change?
> As long as it still works on Debian 8 we shoule ok

Unfortunately, Debian 8 (x86_64) needs it: 
```
vagrant@adoptopenjdkd8:~$ sudo apt install docker.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker.io is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```
I tried running `sudo apt update` too, to no avail

**Comment by sxa** [comment]
Could we lock the installation of the repo down to `Debian >=10` ?

**Comment by Willsparker** [comment]
Done with the latest commit - I've also restricted added the GPG key as well as that isn't needed if the repo isn't being added :-)

**Comment by sxa** [comment]
Running again at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/742/ to test the changes across both Debian versions

**Comment by sxa** [comment]
Looks good - happy for this to be approved if taken out of draft

**Comment by Willsparker** [comment]
Ah ...Okay, I thought Debian 8 had `docker.io` ...

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/749/ 
Both Debians have got passed the `Docker` role

**Pull request merged**
