### PR TITLE
UnixPB: Add support for OpenSUSE12.3

### PR DESCRIPTION
**Pull request by Willsparker**
Should allow for us to build JDKs in an OpenSUSE12.3 Vagrant Machine. I have decided to do this as I was unable to find an OpenSUSE12 or SLES12 vagrant box from https://app.vagrantup.com/boxes/ that served our purposes, therefore I made my own : https://app.vagrantup.com/Willsparker/boxes/OpenSUSE12.3 .

This vagrant box comes with the Virtualbox Guest Additions that allow for the `vboxsf` file system (thereby not having to use `rsync` like `FreeBSD`), as well as having defined repositories meaning we don't have to rely on online ones. 

With this PR is the changes made to the Unix playbooks to allow for this Vagrant machine to run through the playbook and build (at least) JDK8 HS/J9 (currently untested on anything else). As the changes required were so extensive and as not to overwrite the work done in #1062 , I added `openSUSE` to the `../Common/` roles, those these were based off the `SLES.yml` files in the Common role.

### CODE REVIEW

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=SUSE12,label=vagrant/338/

Ran through the playbook okay. Still some Issues with the build that I'll need to look over ...

**Comment by Willsparker** [comment]
The particular issue i'm finding is that `freetype` appears to be installing correctly, and I can find it within the VM, however the build script is looking for `libfreetype.so.` within `openjdk-build/workspace/./build//installedfreetype/lib`, however it's in `openjdk-build/workspace/./build//installedfreetype/lib64`

**Comment by Willsparker** [comment]
With https://github.com/AdoptOpenJDK/openjdk-build/pull/1487 being merged, the playbook succeeded on building with openjdk-8 openJ9 : https://ci.adoptopenjdk.net/view/work%20in%20progress/job/VagrantPlaybookCheck/OS=SUSE12,label=vagrant/344/console

**Comment by sxa555** [comment]
Will approve once conflicts resolved

**Pull request merged**
