### PR TITLE
UnixPB: Add names to all the debug tasks to satisfy linter

### PR DESCRIPTION
**Pull request by Willsparker**
Ref: https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1615799692134600
Useful Materials:
- https://ansible-lint.readthedocs.io/en/latest/default_rules.html#unnamed-task
- https://ansible-lint.readthedocs.io/en/latest/rules.html#false-positives-skipping-rules

The linter has been failing recently, complaining about debug messages that are unnamed. This PR is just checking to see if the `#noqa` syntax will correctly fix the issue. Initially, I have just done this on the debug messages on the AIX playbook, but if it works, I'll do it with the rest of them (or give them names if they require it).

### CODE REVIEW

**Comment by Willsparker** [comment]
Before this PR, the linter was reporting 27/28 Issues. It is still annoyingly reporting that.
It seems the `# noqa [task]` syntax isn't working as expected

**Comment by Willsparker** [comment]
When this PR and #2053 are merged, the Linter should be happy. 
If #2053 is merged first, I'll pull in those changes just to double check, so I'll keep this in draft until it's merged

**Comment by Willsparker** [comment]
I've fixed all the unnamed-task errors now, however the linter is still returning exit code 1, with no obvious errors. Possibly due to the deprecation errors?

**Comment by sxa** [comment]
> I've fixed all the unnamed-task errors now, however the linter is still returning exit code 1, with no obvious errors. Possibly due to the deprecation errors?

From the log:
```
ERROR! the playbook: playbooks/aix.yml could not be found
Error: Process completed with exit code 1.
```
I hadn't picked up on this but In https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/2053, aix.yml was renamed (as it's no longer used)
```
ansible/playbooks/aix.yml → ansible/playbooks/aix.yml.old
```
so we need to top the linter referencing it - https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/2067

**Comment by Willsparker** [comment]
Due to #2067 and #2068  , this should be ready for review :-)

**Review by sxa — APPROVED** [review]
I think the CentOS6 failure (SSL connection issue) is unrelated, therefore approving

**Pull request merged**
