### PR TITLE
Updates/cleanups to support Ubuntu 18.04

### PR DESCRIPTION
**Pull request by sxa555**
Fixes (at least partially, maybe not the docker, but should be ok for my aarch64 Ubuntu 18.04 system) https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/530

On Ubuntu 18 this removes openjdk-7 (We can bootstrap with 8 if needed, and adoptopenjdk builds on CentOS/RHEL so not an issue for us) and `libmpfr4` and `libmpfr4-dbg` (although `libmpfr-dev` is still installed, which may pull in any other bits this is needed for anyway)

If any of the missing things end up being needed we can add them back in later, but these changes won't destabilise the current adoptopenjdk infrastructure.

Signed-off-by: Stewart Addison <sxa@uk.ibm.com>

### CODE REVIEW

**Comment by sxa555** [comment]
@jdekonin How so? The OpenJFX stuff needs to be different between U16 and U18 so is consistent, and the s390x stuff was moving definitions to make them consistent across the Ubuntu versions instead of having term separate so I'd argue they are part of the same "Support multiple Ubuntu's" modification :-)

**Comment by jdekonin** [comment]
I guess the addition of the packages `libgstreamer*` would fall under the Updates part of your comment.  Is there something to tie this against issue wise.

For s390, I guess its just the `numactl` package deletion that is of concern, why is that being deleted.

**Comment by sxa555** [comment]
libgstreamer is mentioned in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/530

Good catch on numactl - it's removal was an error possibly while I was resolving a merge conflict - now fixed

**Comment by sxa555** [comment]
It was a merge conflict which I guess no longer exists after something else going in. I was planning to just squash it during the merge in the github UI

**Comment by sxa555** [comment]
I don't think I can easily do it from my git client so would definitely prefer to just do it on the UI

**Pull request merged**
