### PR TITLE
aixPB: fix minimum size test to real minimum of 60G, exit 1 on fail

### PR DESCRIPTION
**Pull request by aixtools**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
@sxa I thought we needed two approvals on this repo?

**Comment by sxa** [comment]
No we've never had that. We don't have enough people active in infra any more to enforce it without causing excess delays

**Review by sxa — APPROVED** [review]
LGTM - Not too controversial :-)

**Pull request merged**
